version: '3'

services:
  soappreact:
    container_name: soapp_react
    image: node:20.9.0-alpine3.18
    working_dir: /app
    ports:
      #- "3000:3000"    
      - "127.0.0.1:3232:3232"    
    volumes:
      - C:\software\soapp_react:/app
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    #command: sh -c "yarn install && yarn dev"
    #["ng", "serve", "--host", "0.0.0.0"]
    command: ["yarn", "dev", "--host", "0.0.0.0"]

#docker container run --name soapp_react -w /app -p 3232:3232 -v C:\software\soapp_react:/app node:20.9.0-alpine3.18 sh -c "yarn dev"
