export const ReportSection = {
    NUEVOINGRESO: 'EVIDENCIAS INDUCCIÓN Y PREPARACIÓN EMPLEADOS',
    EXAMENESMEDICOS: '5.2 EXÁMENES MEDICO OCUPACIONAL',
    WORKEVENT: 'ACCIDENTE-INCIDENTE-ENFERMEDAD',        
    RETIRED: 'EVIDENCIAS RETIRO EMPLEADOS',
}