export const ReportSection = {
    NUEVOINGRESO: 'EVIDENCIAS INDUCCIÓN Y PREPARACIÓN EMPLEADOS',
    RETIRED: 'EVIDENCIAS RETIRO EMPLEADOS',
    EXAMENESMEDICOS: '5.2 EXÁMENES MEDICO OCUPACIONAL',
    customer: 2,
    cliente: 2,
    agente: 3,
}